### PR TITLE
adding circleci docs building

### PR DESCRIPTION
**Pull request by choldgraf**
This adds a CircleCI job that builds the jupyter-sphinx documentation so that we can preview it

### CODE REVIEW

**Comment by choldgraf** [comment]
Here's the docs preview: https://8-73843754-gh.circle-artifacts.com/0/html/index.html

**Comment by akhmerov** [comment]
Nice! Is there an easy way to get the URL without going via build logs?

**Comment by choldgraf** [comment]
the artifacts redirector action should do this...I'm not sure why it isn't showing up in this PR, but maybe circle needs to be working on Master before it will work? We can try merging this and I can debug if need be

**Comment by akhmerov** [comment]
Sounds good, merging.

**Pull request merged**
