### PR TITLE
Include default values

### PR DESCRIPTION
**Pull request by maartenbreddels**
This might also fix issue #6  I guess the default also need to be in the js side, but I guess nobody does this.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Hum, that should not be necessary. The trick for your widget to work without using the default value is to provide them on the js side from the `default()` option. Numerous examples in ipywidgets, bqplot etc...

**Comment by maartenbreddels** [comment]
But it is not consistent with the 'Embed widget' functionality in the notebook, that includes the whole state. 
What is actually the idea behind having the defaults at both the js and py side?

**Comment by SylvainCorlay** [comment]
> But it is not consistent with the 'Embed widget' functionality in the notebook, that includes the whole state.

Actually it is consistent, except that if you don't specify default values on the js side, everything is considered different from the default value...

**Comment by maartenbreddels** [comment]
Well, from a user point of view it is not consistent. I a piece of code, run it in the notebook, embed it in a html page and it works (full state is in the json). I take the same code, put it in the documentation and it doesn't work.
But I'll stop whining and add the defaults to the js side as well 😉

**Comment by SylvainCorlay** [comment]
Adding the default values will help you for the backward compatibility issues too. You will be able to add new model attributes on the js side while remaining compatible with the same version of the backend.

**Pull request closed without merging**
