### PR TITLE
🚀 RLS: v0.3.2

### PR DESCRIPTION
**Pull request by choldgraf**
this gets in the bugfix for the `download` role. If @akhmerov is 👍 on this then I'll make a release so this gets pushed to pypi

### CODE REVIEW

**Review by akhmerov — APPROVED** [review]
Sounds good. I was thinking about other possible fixes, but there's no reason to hold this off.

**Comment by choldgraf** [comment]
yeah benefits of making the release process as easy as possible is we can make more releases in general :-)

**Comment by choldgraf** [comment]
OK if tests pass I will merge and cut a new release

**Comment by choldgraf** [comment]
@akhmerov any idea why the tests would suddenly start failing on windows?

**Comment by akhmerov** [comment]
#147 some weird kernel messaging timeouts, that trigger once in a while.

**Comment by akhmerov** [comment]
Eh, wrong reference, here's the correct issue: #157

**Comment by choldgraf** [comment]
ok the re-boot of the test is happy, so I'm gonna merge!

**Pull request merged**
