### PR TITLE
Checking if the image path is inside a subdir of dir

### PR DESCRIPTION
**Pull request by AakashGfude**
Related to the discussion here, https://github.com/ExecutableBookProject/MyST-NB/pull/165

cc: @choldgraf @akhmerov

### CODE REVIEW

**Comment by akhmerov** [comment]
Thanks! Do you have an idea whether and how this could be tested?

**Comment by AakashGfude** [comment]
@akhmerov sure. I will go through the test suite of this repo and see if I can add something targeting this.

**Comment by AakashGfude** [comment]
@akhmerov @choldgraf what do you think about the test added ?

**Comment by akhmerov** [comment]
The text looks OK to me. It doesn't verify that sphinx with latex would actually work, but neither do the tests right now.

**Comment by AakashGfude** [comment]
@akhmerov I just narrowed down the test to check this particular thing irrelevant to any builder. 
I was thinking of checking the complete latex build, but then I will have to make edits to the `doctree` fixture, to take an array of `sources` and option to create multiple files in different paths. 
If this is something you don't mind having, then we can do it later.

**Comment by akhmerov** [comment]
@AakashGfude, I agree with your choice. I think it's all good to go.

**Pull request merged**
