### PR TITLE
Fix script outputs

### PR DESCRIPTION
**Pull request by chrisjsewell**
v0.3.2 please lol

### CODE REVIEW

**Comment by akhmerov** [comment]
Good idea. I am wondering: wouldn't it be better to send this via nbconvert script export though?

**Comment by chrisjsewell** [comment]
What extra would that give you?

**Comment by akhmerov** [comment]
AFAIU non-code cells would be left as comments.

**Comment by chrisjsewell** [comment]
How does it no for every programming language though what the comment syntax is?

**Comment by akhmerov** [comment]
Looking at the [source](https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/script.py#L33-L36) via an entry point. I presume these would typically be provided by the kernel package, e.g. nbconvert docs specifically mention Julia.

**Comment by chrisjsewell** [comment]
Well if it works, then yeh go for it, just make sure that it falls back on outputting the code only (with the correct file extension)

**Comment by akhmerov** [comment]
Closing in favor of #160

**Pull request closed without merging**
